version: '1'
services:
  translation-service:
    build: .
    image: ghcr.io/ndph-arts/translation-service:${TRANSLATION_SERVICE_TAG}
    container_name: translation-service
    domainname: ndph-arts-${CI_REF_SLUG}
    depends_on:
      - postgres
    environment:
#      JDBC_URL: "jdbc:postgresql://postgres:5432/arts?user=ndph@arts-db&password=England99!"
#      JDBC_URL: jdbc:postgresql://arts-db.postgres.database.azure.com:5432/arts?user=ndph@arts-db&password=England99!
      JDBC_URL: jdbc:postgresql://ndph-arts-${CI_REF_SLUG}.uksouth.azurecontainer.io:5432/arts?user=ndph@arts-db&password=England99!
      JDBC_DRIVER: "org.postgresql.Driver"
      SERVER_PORT: "80"
    ports:
      - "80:80"

  postgres:
    image: postgres
    domainname: ndph-arts-${CI_REF_SLUG}
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "England99!"
      POSTGRES_USER: "ndph@arts-db"
      POSTGRES_DB: "arts"
    ports:
      - "5432:5432"
