name: Deploy to Azure from GHCR

on:
  registry_package:
    types: [updated,published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: ${{REPO_NAME}} == 'ndph/translation-service'
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'mts-translation-service'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: 'ghcr.io/ndph-arts/translation-service:${{ github.sha }}'

