name: Deploy to Azure from GHCR

on:
  registry_package:
    types: [updated,published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.registry_package.package.name == 'translation-service'
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'translation-service'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: 'ghcr.io/I tndph-arts/translation-service:${{ github.sha }}'
